-- ============================================================
-- MIGRATION: 20260222000003_missing_tables.sql
-- Tables et colonnes manquantes identifiées à l'audit
-- ============================================================

-- 1. CONNECTION LOGS (utilisée par backend/src/auth/auth.service.ts)
CREATE TABLE IF NOT EXISTS public.connection_logs (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id     UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    email       TEXT,
    device      TEXT,
    ip_address  TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CUSTOMER ADDRESSES (utilisée par lollyshop)
CREATE TABLE IF NOT EXISTS public.customer_addresses (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id  UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    address     TEXT NOT NULL,
    city        TEXT,
    postal_code TEXT,
    country     TEXT DEFAULT 'Sénégal',
    is_default  BOOLEAN DEFAULT FALSE,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 3. SUPPLIERS (utilisée par luxya-pos/purchase-orders)
CREATE TABLE IF NOT EXISTS public.suppliers (
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name           TEXT NOT NULL,
    contact_person TEXT,
    phone          TEXT,
    email          TEXT,
    address        TEXT,
    shop_id        BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
    created_at     TIMESTAMPTZ DEFAULT NOW(),
    updated_at     TIMESTAMPTZ DEFAULT NOW()
);

DROP TRIGGER IF EXISTS update_suppliers_updated_at ON public.suppliers;
CREATE TRIGGER update_suppliers_updated_at
    BEFORE UPDATE ON public.suppliers
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 4. PURCHASE ORDERS (utilisée par luxya-pos/purchase-orders)
CREATE TABLE IF NOT EXISTS public.purchase_orders (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    supplier_id BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL,
    shop_id     BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
    status      TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'ordered', 'received', 'cancelled')),
    notes       TEXT,
    received_at TIMESTAMPTZ,
    created_by  UUID REFERENCES public.profiles(id),
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 5. PURCHASE ORDER ITEMS
CREATE TABLE IF NOT EXISTS public.purchase_order_items (
    id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    purchase_order_id BIGINT NOT NULL REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
    product_id        BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    quantity          INTEGER NOT NULL CHECK (quantity > 0),
    cost_price        NUMERIC NOT NULL CHECK (cost_price >= 0),
    received_quantity INTEGER DEFAULT 0,
    created_at        TIMESTAMPTZ DEFAULT NOW()
);

-- 6. PRODUCT VIEWS (utilisée par backend/src/products/products.service.ts)
CREATE TABLE IF NOT EXISTS public.product_views (
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    shop_id    BIGINT REFERENCES public.shops(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- COLONNES MANQUANTES SUR LES TABLES EXISTANTES
-- ============================================================

-- profiles: téléphone et code parrainage
ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS phone TEXT,
    ADD COLUMN IF NOT EXISTS referral_code TEXT UNIQUE;

-- customers: updated_at manquant
ALTER TABLE public.customers
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

DROP TRIGGER IF EXISTS update_customers_updated_at ON public.customers;
CREATE TRIGGER update_customers_updated_at
    BEFORE UPDATE ON public.customers
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- expenses: date de dernière automation pour les dépenses récurrentes
ALTER TABLE public.expenses
    ADD COLUMN IF NOT EXISTS last_automated_at TIMESTAMPTZ;

-- cash_movements: méthode de paiement et créateur (utilisés dans luxya-pos)
ALTER TABLE public.cash_movements
    ADD COLUMN IF NOT EXISTS payment_method TEXT,
    ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES public.profiles(id);

-- products: colonne created_by manquante dans la migration initiale
ALTER TABLE public.products
    ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES public.profiles(id);

-- ============================================================
-- STORAGE BUCKET: PRODUCTS
-- ============================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('products', 'products', TRUE)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Enable public read access for product images" ON storage.objects;
CREATE POLICY "Enable public read access for product images" ON storage.objects
    FOR SELECT TO public
    USING (bucket_id = 'products');

DROP POLICY IF EXISTS "Enable authenticated insert for product images" ON storage.objects;
CREATE POLICY "Enable authenticated insert for product images" ON storage.objects
    FOR INSERT TO authenticated
    WITH CHECK (bucket_id = 'products' AND (SELECT public.check_is_admin()));

DROP POLICY IF EXISTS "Enable authenticated delete for product images" ON storage.objects;
CREATE POLICY "Enable authenticated delete for product images" ON storage.objects
    FOR DELETE TO authenticated
    USING (bucket_id = 'products' AND (SELECT public.check_is_admin()));

-- ============================================================
-- RLS POUR LES NOUVELLES TABLES
-- ============================================================

ALTER TABLE public.connection_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_views ENABLE ROW LEVEL SECURITY;

-- connection_logs: admins only
DROP POLICY IF EXISTS "Admins only: Connection Logs" ON public.connection_logs;
CREATE POLICY "Admins only: Connection Logs" ON public.connection_logs
    FOR ALL TO authenticated
    USING (public.check_is_admin());

-- customer_addresses: utilisateur voit ses propres adresses
DROP POLICY IF EXISTS "Personal: Customer Addresses" ON public.customer_addresses;
CREATE POLICY "Personal: Customer Addresses" ON public.customer_addresses
    FOR ALL TO authenticated
    USING (auth.uid() = profile_id)
    WITH CHECK (auth.uid() = profile_id);

-- suppliers: isolation par boutique
DROP POLICY IF EXISTS "Universal Shop Isolation: Suppliers" ON public.suppliers;
CREATE POLICY "Universal Shop Isolation: Suppliers" ON public.suppliers
    FOR ALL TO authenticated
    USING (public.check_is_admin() OR shop_id = ANY(public.get_user_authorized_shops()))
    WITH CHECK (public.check_is_admin() OR shop_id = ANY(public.get_user_authorized_shops()));

-- purchase_orders: isolation par boutique
DROP POLICY IF EXISTS "Universal Shop Isolation: Purchase Orders" ON public.purchase_orders;
CREATE POLICY "Universal Shop Isolation: Purchase Orders" ON public.purchase_orders
    FOR ALL TO authenticated
    USING (public.check_is_admin() OR shop_id = ANY(public.get_user_authorized_shops()))
    WITH CHECK (public.check_is_admin() OR shop_id = ANY(public.get_user_authorized_shops()));

-- purchase_order_items: via purchase_order
DROP POLICY IF EXISTS "Universal Shop Isolation: Purchase Order Items" ON public.purchase_order_items;
CREATE POLICY "Universal Shop Isolation: Purchase Order Items" ON public.purchase_order_items
    FOR ALL TO authenticated
    USING (
        public.check_is_admin() OR EXISTS (
            SELECT 1 FROM public.purchase_orders po
            WHERE po.id = purchase_order_id
            AND po.shop_id = ANY(public.get_user_authorized_shops())
        )
    );

-- product_views: lecture publique, écriture authentifiée
DROP POLICY IF EXISTS "Public read: Product Views" ON public.product_views;
CREATE POLICY "Public read: Product Views" ON public.product_views
    FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Authenticated insert: Product Views" ON public.product_views;
CREATE POLICY "Authenticated insert: Product Views" ON public.product_views
    FOR INSERT TO public WITH CHECK (true);

-- ============================================================
NOTIFY pgrst, 'reload schema';
