-- ============================================================
-- LUXIA POS & LOLLY AGENCY - CONSOLIDATED INITIAL SCHEMA v1.1
-- Includes POS, Agency, and E-commerce modules
-- Created: 2026-02-22
-- ============================================================

-- 0. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. BASE TABLES: SHOPS & USERS
CREATE TABLE IF NOT EXISTS public.shops (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    logo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    full_name TEXT,
    role TEXT DEFAULT 'cashier' CHECK (role IN ('admin', 'manager', 'cashier', 'client')),
    user_type TEXT DEFAULT 'staff' CHECK (user_type IN ('staff', 'client')),
    shop_id BIGINT REFERENCES public.shops(id),
    shop_ids BIGINT[] DEFAULT '{}',
    is_super_admin BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    has_stock_access BOOLEAN DEFAULT FALSE,
    loyalty_points INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. INVENTORY: PRODUCTS & CATEGORIES
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC DEFAULT 0,
    promo_price NUMERIC DEFAULT 0,
    cost_price NUMERIC DEFAULT 0,
    stock INTEGER DEFAULT 0,
    min_stock INTEGER DEFAULT 2,
    category TEXT,
    brand TEXT,
    shop_id BIGINT REFERENCES public.shops(id),
    image TEXT,
    images TEXT[] DEFAULT '{}',
    video_url TEXT,
    type TEXT DEFAULT 'product',
    show_on_pos BOOLEAN DEFAULT true,
    show_on_website BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    expiry_date DATE,
    variants JSONB DEFAULT '[]',
    sales_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CUSTOMERS & DEBTS
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    address TEXT,
    ninea TEXT,
    rc TEXT,
    loyalty_points INTEGER DEFAULT 0,
    shop_id BIGINT REFERENCES public.shops(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.debts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
    shop_id BIGINT REFERENCES public.shops(id),
    total_amount NUMERIC DEFAULT 0,
    paid_amount NUMERIC DEFAULT 0,
    remaining_amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'pending',
    type TEXT DEFAULT 'receivable',
    description TEXT,
    due_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. SALES & REVENUE
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    total_amount NUMERIC NOT NULL,
    paid_amount NUMERIC DEFAULT 0,
    payment_method TEXT DEFAULT 'cash',
    shop_id BIGINT REFERENCES public.shops(id),
    customer_id BIGINT REFERENCES public.customers(id),
    customer_name TEXT,
    created_by UUID REFERENCES public.profiles(id),
    status TEXT DEFAULT 'completed',
    type TEXT DEFAULT 'sale', 
    invoice_number TEXT UNIQUE,
    parent_id BIGINT REFERENCES public.sales(id),
    with_tva BOOLEAN DEFAULT true,
    shipping_cost NUMERIC DEFAULT 0,
    shipping_method TEXT,
    coupon_id UUID,
    project_id UUID, 
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sale_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sale_id BIGINT REFERENCES public.sales(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    quantity INTEGER NOT NULL,
    price NUMERIC NOT NULL,
    variant_id TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. EXPENSES
CREATE TABLE IF NOT EXISTS public.expense_categories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    shop_id BIGINT REFERENCES public.shops(id),
    is_personal BOOLEAN DEFAULT false,
    budget NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    category TEXT,
    date TIMESTAMPTZ DEFAULT NOW(),
    shop_id BIGINT REFERENCES public.shops(id),
    created_by UUID REFERENCES public.profiles(id),
    is_recurring BOOLEAN DEFAULT false,
    frequency TEXT,
    project_id UUID 
);

-- 6. CASH MANAGEMENT
CREATE TABLE IF NOT EXISTS public.cash_sessions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    shop_id BIGINT REFERENCES public.shops(id),
    opened_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    closed_at TIMESTAMPTZ,
    opening_balance NUMERIC DEFAULT 0 NOT NULL,
    closing_balance_theoretical NUMERIC DEFAULT 0,
    closing_balance_actual NUMERIC,
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    opened_by UUID REFERENCES auth.users(id),
    closed_by UUID REFERENCES auth.users(id),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.cash_movements (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id BIGINT REFERENCES public.cash_sessions(id) ON DELETE CASCADE,
    shop_id BIGINT REFERENCES public.shops(id),
    type TEXT NOT NULL CHECK (type IN ('income', 'outcome', 'deposit', 'withdrawal')),
    amount NUMERIC NOT NULL,
    description TEXT,
    source TEXT CHECK (source IN ('sale', 'expense', 'debt_payment', 'manual')),
    source_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.debt_payments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    debt_id BIGINT REFERENCES public.debts(id) ON DELETE CASCADE,
    session_id BIGINT REFERENCES public.cash_sessions(id),
    amount NUMERIC NOT NULL,
    payment_method TEXT DEFAULT 'cash',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. AGENCY PROJECT MANAGEMENT
CREATE TABLE IF NOT EXISTS public.agency_projects (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        TEXT NOT NULL,
    client_id   BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    type        TEXT NOT NULL DEFAULT 'client' CHECK (type IN ('client', 'agence')),
    status      TEXT NOT NULL DEFAULT 'en_cours' CHECK (status IN ('planifie', 'en_cours', 'termine', 'annule')),
    budget      NUMERIC(12,2),
    description TEXT,
    start_date  DATE,
    end_date    DATE,
    shop_id     BIGINT REFERENCES public.shops(id),
    created_by  UUID REFERENCES public.profiles(id),
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.agency_stages (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES public.agency_projects(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    position   INTEGER NOT NULL DEFAULT 0,
    status     TEXT NOT NULL DEFAULT 'en_cours' CHECK (status IN ('en_cours', 'termine')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.agency_tasks (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    stage_id     UUID NOT NULL REFERENCES public.agency_stages(id) ON DELETE CASCADE,
    title        TEXT NOT NULL,
    description  TEXT,
    status       TEXT NOT NULL DEFAULT 'todo' CHECK (status IN ('todo', 'in_progress', 'done')),
    priority     TEXT NOT NULL DEFAULT 'normale' CHECK (priority IN ('basse', 'normale', 'haute', 'urgente')),
    assignee_id  UUID REFERENCES public.profiles(id),
    deadline     DATE,
    position     INTEGER NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.agency_task_links (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    from_task_id UUID NOT NULL REFERENCES public.agency_tasks(id) ON DELETE CASCADE,
    to_task_id   UUID NOT NULL REFERENCES public.agency_tasks(id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(from_task_id, to_task_id),
    CHECK (from_task_id != to_task_id)
);

CREATE TABLE IF NOT EXISTS public.agency_task_comments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    task_id UUID NOT NULL REFERENCES public.agency_tasks(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.agency_project_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    template_data JSONB NOT NULL,
    shop_id BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
    created_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. E-COMMERCE MODULES
CREATE TABLE IF NOT EXISTS public.shipping_zones (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    free_threshold NUMERIC,
    estimated_days TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.coupons (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    discount_type TEXT CHECK (discount_type IN ('percentage', 'fixed')) NOT NULL,
    discount_value NUMERIC NOT NULL,
    min_purchase NUMERIC DEFAULT 0,
    max_uses INTEGER,
    used_count INTEGER DEFAULT 0,
    expiry_date TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.product_reviews (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
    comment TEXT,
    status TEXT CHECK (status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.wishlist (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(profile_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.loyalty_history (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    points_change INTEGER NOT NULL,
    reason TEXT NOT NULL,
    sale_id BIGINT REFERENCES public.sales(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. SITE SETTINGS
CREATE TABLE IF NOT EXISTS public.site_settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    content JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Initialisation de la configuration du site si elle n'existe pas
INSERT INTO public.site_settings (name, content)
VALUES 
    ('lolly_shop_config',
    '{
        "announcement": "BIENVENUE CHEZ LOLLY SAS",
        "slides": [],
        "event": {
            "title": "",
            "subtitle": "",
            "image": "",
            "mini_image": "",
            "link": "/"
        },
        "category_groups": []
    }'::jsonb
)
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- HELPER FUNCTIONS & TRIGGERS
-- ============================================================

-- A. UPDATED_AT TRIGGER
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_products_updated_at ON public.products;
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_agency_projects_updated_at ON public.agency_projects;
CREATE TRIGGER update_agency_projects_updated_at BEFORE UPDATE ON public.agency_projects FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_agency_tasks_updated_at ON public.agency_tasks;
CREATE TRIGGER update_agency_tasks_updated_at BEFORE UPDATE ON public.agency_tasks FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- B. AUTOMATED STOCK MANAGEMENT
CREATE OR REPLACE FUNCTION public.proc_decrement_stock(p_id BIGINT, p_qty INT, p_variant_id TEXT DEFAULT NULL)
RETURNS VOID AS $$
BEGIN
    UPDATE public.products SET stock = COALESCE(stock, 0) - p_qty WHERE id = p_id AND type != 'service';
    IF p_variant_id IS NOT NULL THEN
        UPDATE public.products SET variants = (
            SELECT jsonb_agg(CASE WHEN (v->>'id')::text = p_variant_id THEN jsonb_set(v, '{stock}', (COALESCE((v->>'stock')::int, 0) - p_qty)::text::jsonb) ELSE v END)
            FROM jsonb_array_elements(variants) v
        ) WHERE id = p_id;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.proc_increment_stock(p_id BIGINT, p_qty INT, p_variant_id TEXT DEFAULT NULL)
RETURNS VOID AS $$
BEGIN
    UPDATE public.products SET stock = COALESCE(stock, 0) + p_qty WHERE id = p_id AND type != 'service';
    IF p_variant_id IS NOT NULL THEN
        UPDATE public.products SET variants = (
            SELECT jsonb_agg(CASE WHEN (v->>'id')::text = p_variant_id THEN jsonb_set(v, '{stock}', (COALESCE((v->>'stock')::int, 0) + p_qty)::text::jsonb) ELSE v END)
            FROM jsonb_array_elements(variants) v
        ) WHERE id = p_id;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.handle_sale_item_stock_change()
RETURNS TRIGGER AS $$
DECLARE v_sale_type TEXT; v_sale_status TEXT;
BEGIN
    SELECT type, status INTO v_sale_type, v_sale_status FROM public.sales WHERE id = COALESCE(NEW.sale_id, OLD.sale_id);
    IF v_sale_type = 'quote' OR v_sale_status = 'cancelled' THEN RETURN COALESCE(NEW, OLD); END IF;
    IF (TG_OP = 'INSERT') THEN
        IF NEW.product_id IS NOT NULL THEN
            PERFORM public.proc_decrement_stock(NEW.product_id, NEW.quantity, NEW.variant_id);
            UPDATE public.products SET sales_count = COALESCE(sales_count, 0) + NEW.quantity WHERE id = NEW.product_id;
        END IF;
    ELSIF (TG_OP = 'DELETE') THEN
        IF OLD.product_id IS NOT NULL THEN
            PERFORM public.proc_increment_stock(OLD.product_id, OLD.quantity, OLD.variant_id);
            UPDATE public.products SET sales_count = GREATEST(0, COALESCE(sales_count, 0) - OLD.quantity) WHERE id = OLD.product_id;
        END IF;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sale_items_stock ON public.sale_items;
CREATE TRIGGER trg_sale_items_stock AFTER INSERT OR DELETE ON public.sale_items FOR EACH ROW EXECUTE FUNCTION public.handle_sale_item_stock_change();

-- C. LOYALTY POINTS AUTOMATION
CREATE OR REPLACE FUNCTION public.credit_loyalty_points()
RETURNS TRIGGER AS $$
DECLARE points_to_add INTEGER;
BEGIN
    IF (NEW.customer_id IS NOT NULL AND NEW.status = 'completed' AND (OLD.status IS NULL OR OLD.status != 'completed')) THEN
        points_to_add := FLOOR(NEW.total_amount / 100);
        IF points_to_add > 0 THEN
            UPDATE public.profiles SET loyalty_points = COALESCE(loyalty_points, 0) + points_to_add WHERE id = NEW.customer_id;
            INSERT INTO public.loyalty_history (profile_id, points_change, reason, sale_id)
            VALUES (NEW.customer_id, points_to_add, 'Achat boutique / Commande #' || NEW.id, NEW.id);
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_sale_completed_loyalty ON public.sales;
CREATE TRIGGER on_sale_completed_loyalty AFTER UPDATE ON public.sales FOR EACH ROW EXECUTE FUNCTION public.credit_loyalty_points();

-- D. SECURITY HELPERS
CREATE OR REPLACE FUNCTION public.check_is_admin() RETURNS BOOLEAN AS $$
    SELECT COALESCE(role = 'admin' OR is_super_admin, false) FROM public.profiles WHERE id = auth.uid();
$$ LANGUAGE sql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_user_authorized_shops() RETURNS BIGINT[] AS $$
    SELECT COALESCE(shop_ids, ARRAY[shop_id]) FROM public.profiles WHERE id = auth.uid();
$$ LANGUAGE sql SECURITY DEFINER;
